In [ ]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

In [ ]:
#capture index of word
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[16, 472, 353, 476], [16, 472, 353, 367], [16, 408, 353, 197], [347, 108, 5, 345, 41], [347, 108, 5, 345, 157], [435, 16, 408, 353, 373], [269, 189, 45, 345]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding, pre add 0 at first where as in post 0 is added at last
## converting each vactor length to 8, will add 0 to make make vector length 8
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  16 472 353 476]
 [  0   0   0   0  16 472 353 367]
 [  0   0   0   0  16 408 353 197]
 [  0   0   0 347 108   5 345  41]
 [  0   0   0 347 108   5 345 157]
 [  0   0   0 435  16 408 353 373]
 [  0   0   0   0 269 189  45 345]]


In [ ]:
## 10 feature representation dimensions
dim=10


In [ ]:
## sent_length is 8 in our case
## Embedding is same like word2Vec
##our data is small so 10 dim is enough
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  16, 472, 353, 476], dtype=int32)

In [ ]:
#let see the feature representation of first vector in 10 dimensions
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 35ms/step


array([[-0.0153698 ,  0.03894879, -0.00121678,  0.02309746,  0.00673712,
         0.0284876 , -0.00782641,  0.03571956, -0.01576704,  0.04021854],
       [-0.0153698 ,  0.03894879, -0.00121678,  0.02309746,  0.00673712,
         0.0284876 , -0.00782641,  0.03571956, -0.01576704,  0.04021854],
       [-0.0153698 ,  0.03894879, -0.00121678,  0.02309746,  0.00673712,
         0.0284876 , -0.00782641,  0.03571956, -0.01576704,  0.04021854],
       [-0.0153698 ,  0.03894879, -0.00121678,  0.02309746,  0.00673712,
         0.0284876 , -0.00782641,  0.03571956, -0.01576704,  0.04021854],
       [ 0.01894646,  0.03336379,  0.04159807, -0.0084645 , -0.0104445 ,
         0.0248468 ,  0.03275425, -0.01559015,  0.04200098,  0.02468151],
       [ 0.00371625, -0.03837893,  0.0094718 ,  0.0229135 ,  0.02327229,
         0.00778663, -0.02169598, -0.03576339, -0.02370013, -0.03084594],
       [ 0.00426846, -0.00992689,  0.03659017, -0.04861131, -0.0002692 ,
         0.02622105, -0.04484042, -0.0038246 

In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 26ms/step
[[[-0.0153698   0.03894879 -0.00121678  0.02309746  0.00673712
    0.0284876  -0.00782641  0.03571956 -0.01576704  0.04021854]
  [-0.0153698   0.03894879 -0.00121678  0.02309746  0.00673712
    0.0284876  -0.00782641  0.03571956 -0.01576704  0.04021854]
  [-0.0153698   0.03894879 -0.00121678  0.02309746  0.00673712
    0.0284876  -0.00782641  0.03571956 -0.01576704  0.04021854]
  [-0.0153698   0.03894879 -0.00121678  0.02309746  0.00673712
    0.0284876  -0.00782641  0.03571956 -0.01576704  0.04021854]
  [ 0.01894646  0.03336379  0.04159807 -0.0084645  -0.0104445
    0.0248468   0.03275425 -0.01559015  0.04200098  0.02468151]
  [ 0.00371625 -0.03837893  0.0094718   0.0229135   0.02327229
    0.00778663 -0.02169598 -0.03576339 -0.02370013 -0.03084594]
  [ 0.00426846 -0.00992689  0.03659017 -0.04861131 -0.0002692
    0.02622105 -0.04484042 -0.0038246   0.04042244  0.04023324]
  [-0.0289596  -0.01060515  0.00240514  0.03944753 -0.0034788